In [1]:
from statsbombpy import sb
import pandas as pd

MATCH_ID = 3943043

lineups = sb.lineups(match_id=MATCH_ID)

E:\Documents\mosda\Projets\Data analyse\Projet 1 -Heatmap de passes d’un défenseur central\central-defender-pass-heatmap\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [2]:
players = []

for team_name, lineup_df in lineups.items():
    temp = lineup_df.copy()
    temp["team"] = team_name
    players.append(temp)

players_df = pd.concat(players, ignore_index=True)

players_df.head()

,player_id,player_name,player_nickname,jersey_number,country,cards,positions,team
0,3042,Mikel Merino Zazón,Mikel Merino,6,Spain,[],"[{'position_id': 17, 'position': 'Right Wing',...",Spain
1,3265,José Luis Sanmartín Mato,Joselu,9,Spain,[],[],Spain
2,3477,Álvaro Borja Morata Martín,Álvaro Morata,7,Spain,[],"[{'position_id': 23, 'position': 'Center Forwa...",Spain
3,4127,David Raya Martin,David Raya,1,Spain,[],[],Spain
4,4353,Aymeric Laporte,NaN,14,Spain,[],"[{'position_id': 5, 'position': 'Left Center B...",Spain

In [3]:
players_df.columns.tolist()

['player_id',
 'player_name',
 'player_nickname',
 'jersey_number',
 'country',
 'cards',
 'positions',
 'team']

In [4]:
players_df["has_played"] = players_df["positions"].apply(
    lambda x: isinstance(x, list) and len(x) > 0
)

players_played = players_df[
    players_df["has_played"]
].copy()

players_played

,player_id,player_name,player_nickname,jersey_number,country,cards,positions,team,has_played
0,3042,Mikel Merino Zazón,Mikel Merino,6,Spain,[],"[{'position_id': 17, 'position': 'Right Wing',...",Spain,True
2,3477,Álvaro Borja Morata Martín,Álvaro Morata,7,Spain,[],"[{'position_id': 23, 'position': 'Center Forwa...",Spain,True
4,4353,Aymeric Laporte,NaN,14,Spain,[],"[{'position_id': 5, 'position': 'Left Center B...",Spain,True
5,5202,José Ignacio Fernández Iglesias,Nacho,4,Spain,[],"[{'position_id': 3, 'position': 'Right Center ...",Spain,True
6,5721,Daniel Carvajal Ramos,Daniel Carvajal,2,Spain,[],"[{'position_id': 2, 'position': 'Right Back', ...",Spain,True
7,6655,Fabián Ruiz Peña,Fabián Ruiz,8,Spain,[],"[{'position_id': 11, 'position': 'Left Defensi...",Spain,True
8,6685,Mikel Oyarzabal Ugarte,Mikel Oyarzabal,21,Spain,[],"[{'position_id': 23, 'position': 'Center Forwa...",Spain,True
10,6765,Rodrigo Hernández Cascante,Rodri,16,Spain,[],"[{'position_id': 9, 'position': 'Right Defensi...",Spain,True
13,11748,Unai Simón Mendibil,Unai Simón,23,Spain,[],"[{'position_id': 1, 'position': 'Goalkeeper', ...",Spain,True
14,16532,Daniel Olmo Carvajal,Daniel Olmo,10,Spain,"[{'time': '29:57', 'card_type': 'Yellow Card',...","[{'position_id': 19, 'position': 'Center Attac...",Spain,True
15,17620,Marc Cucurella Saseta,Marc Cucurella,24,Spain,[],"[{'position_id': 6, 'position': 'Left Back', '...",Spain,True
16,22128,Robin Aime Robert Le Normand,Robin Le Normand,3,Spain,[],"[{'position_id': 3, 'position': 'Right Center ...",Spain,True
17,24921,Martín Zubimendi Ibáñez,Martín Zubimendi,18,Spain,[],"[{'position_id': 9, 'position': 'Right Defensi...",Spain,True
21,68574,Nicholas Williams Arthuer,Nico Williams,17,Spain,[],"[{'position_id': 21, 'position': 'Left Wing', ...",Spain,True
23,316046,Lamine Yamal Nasraoui Ebana,Lamine Yamal,19,Spain,[],"[{'position_id': 17, 'position': 'Right Wing',...",Spain,True
25,3205,Kyle Walker,NaN,2,England,[],"[{'position_id': 2, 'position': 'Right Back', ...",England,True
26,3244,John Stones,NaN,5,England,"[{'time': '52:31', 'card_type': 'Yellow Card',...","[{'position_id': 3, 'position': 'Right Center ...",England,True
28,3382,Luke Shaw,NaN,3,England,[],"[{'position_id': 6, 'position': 'Left Back', '...",England,True
29,3468,Jordan Pickford,NaN,1,England,[],"[{'position_id': 1, 'position': 'Goalkeeper', ...",England,True
33,3834,Ivan Toney,NaN,17,England,[],"[{'position_id': 21, 'position': 'Left Wing', ...",England,True
34,3943,Declan Rice,NaN,4,England,[],"[{'position_id': 11, 'position': 'Left Defensi...",England,True
36,4354,Phil Foden,NaN,11,England,[],"[{'position_id': 19, 'position': 'Center Attac...",England,True
37,4760,Ollie Watkins,NaN,19,England,"[{'time': '90:54', 'card_type': 'Yellow Card',...","[{'position_id': 23, 'position': 'Center Forwa...",England,True
40,10955,Harry Kane,NaN,9,England,"[{'time': '24:38', 'card_type': 'Yellow Card',...","[{'position_id': 23, 'position': 'Center Forwa...",England,True
41,22084,Bukayo Saka,NaN,7,England,[],"[{'position_id': 17, 'position': 'Right Wing',...",England,True
45,30714,Jude Bellingham,NaN,10,England,[],"[{'position_id': 21, 'position': 'Left Wing', ...",England,True
46,34526,Marc Guehi,NaN,6,England,[],"[{'position_id': 5, 'position': 'Left Center B...",England,True
47,39461,Cole Palmer,NaN,24,England,[],"[{'position_id': 9, 'position': 'Right Defensi...",England,True
49,99174,Kobbie Mainoo,NaN,26,England,[],"[{'position_id': 9, 'position': 'Right Defensi...",England,True

In [5]:
players_played[
    [
        "team",
        "player_name",
        "jersey_number",
        "country",
        "positions"
    ]
]

,team,player_name,jersey_number,country,positions
0,Spain,Mikel Merino Zazón,6,Spain,"[{'position_id': 17, 'position': 'Right Wing',..."
2,Spain,Álvaro Borja Morata Martín,7,Spain,"[{'position_id': 23, 'position': 'Center Forwa..."
4,Spain,Aymeric Laporte,14,Spain,"[{'position_id': 5, 'position': 'Left Center B..."
5,Spain,José Ignacio Fernández Iglesias,4,Spain,"[{'position_id': 3, 'position': 'Right Center ..."
6,Spain,Daniel Carvajal Ramos,2,Spain,"[{'position_id': 2, 'position': 'Right Back', ..."
7,Spain,Fabián Ruiz Peña,8,Spain,"[{'position_id': 11, 'position': 'Left Defensi..."
8,Spain,Mikel Oyarzabal Ugarte,21,Spain,"[{'position_id': 23, 'position': 'Center Forwa..."
10,Spain,Rodrigo Hernández Cascante,16,Spain,"[{'position_id': 9, 'position': 'Right Defensi..."
13,Spain,Unai Simón Mendibil,23,Spain,"[{'position_id': 1, 'position': 'Goalkeeper', ..."
14,Spain,Daniel Olmo Carvajal,10,Spain,"[{'position_id': 19, 'position': 'Center Attac..."
15,Spain,Marc Cucurella Saseta,24,Spain,"[{'position_id': 6, 'position': 'Left Back', '..."
16,Spain,Robin Aime Robert Le Normand,3,Spain,"[{'position_id': 3, 'position': 'Right Center ..."
17,Spain,Martín Zubimendi Ibáñez,18,Spain,"[{'position_id': 9, 'position': 'Right Defensi..."
21,Spain,Nicholas Williams Arthuer,17,Spain,"[{'position_id': 21, 'position': 'Left Wing', ..."
23,Spain,Lamine Yamal Nasraoui Ebana,19,Spain,"[{'position_id': 17, 'position': 'Right Wing',..."
25,England,Kyle Walker,2,England,"[{'position_id': 2, 'position': 'Right Back', ..."
26,England,John Stones,5,England,"[{'position_id': 3, 'position': 'Right Center ..."
28,England,Luke Shaw,3,England,"[{'position_id': 6, 'position': 'Left Back', '..."
29,England,Jordan Pickford,1,England,"[{'position_id': 1, 'position': 'Goalkeeper', ..."
33,England,Ivan Toney,17,England,"[{'position_id': 21, 'position': 'Left Wing', ..."
34,England,Declan Rice,4,England,"[{'position_id': 11, 'position': 'Left Defensi..."
36,England,Phil Foden,11,England,"[{'position_id': 19, 'position': 'Center Attac..."
37,England,Ollie Watkins,19,England,"[{'position_id': 23, 'position': 'Center Forwa..."
40,England,Harry Kane,9,England,"[{'position_id': 23, 'position': 'Center Forwa..."
41,England,Bukayo Saka,7,England,"[{'position_id': 17, 'position': 'Right Wing',..."
45,England,Jude Bellingham,10,England,"[{'position_id': 21, 'position': 'Left Wing', ..."
46,England,Marc Guehi,6,England,"[{'position_id': 5, 'position': 'Left Center B..."
47,England,Cole Palmer,24,England,"[{'position_id': 9, 'position': 'Right Defensi..."
49,England,Kobbie Mainoo,26,England,"[{'position_id': 9, 'position': 'Right Defensi..."

In [6]:
def extract_main_position(positions):
    if isinstance(positions, list) and len(positions) > 0:
        return positions[0].get("position")
    return None

In [7]:
players_played["main_position"] = players_played["positions"].apply(
    extract_main_position
)

In [8]:
players_played_clean = players_played[
    [
        "team",
        "player_id",
        "player_name",
        "jersey_number",
        "main_position"
    ]
].sort_values(
    by=["team", "jersey_number"]
)

players_played_clean

,team,player_id,player_name,jersey_number,main_position
29,England,3468,Jordan Pickford,1,Goalkeeper
25,England,3205,Kyle Walker,2,Right Back
28,England,3382,Luke Shaw,3,Left Back
34,England,3943,Declan Rice,4,Left Defensive Midfield
26,England,3244,John Stones,5,Right Center Back
46,England,34526,Marc Guehi,6,Left Center Back
41,England,22084,Bukayo Saka,7,Right Wing
40,England,10955,Harry Kane,9,Center Forward
45,England,30714,Jude Bellingham,10,Left Wing
36,England,4354,Phil Foden,11,Center Attacking Midfield
33,England,3834,Ivan Toney,17,Left Wing
37,England,4760,Ollie Watkins,19,Center Forward
47,England,39461,Cole Palmer,24,Right Defensive Midfield
49,England,99174,Kobbie Mainoo,26,Right Defensive Midfield
6,Spain,5721,Daniel Carvajal Ramos,2,Right Back
16,Spain,22128,Robin Aime Robert Le Normand,3,Right Center Back
5,Spain,5202,José Ignacio Fernández Iglesias,4,Right Center Back
0,Spain,3042,Mikel Merino Zazón,6,Right Wing
2,Spain,3477,Álvaro Borja Morata Martín,7,Center Forward
7,Spain,6655,Fabián Ruiz Peña,8,Left Defensive Midfield
14,Spain,16532,Daniel Olmo Carvajal,10,Center Attacking Midfield
4,Spain,4353,Aymeric Laporte,14,Left Center Back
10,Spain,6765,Rodrigo Hernández Cascante,16,Right Defensive Midfield
21,Spain,68574,Nicholas Williams Arthuer,17,Left Wing
17,Spain,24921,Martín Zubimendi Ibáñez,18,Right Defensive Midfield
23,Spain,316046,Lamine Yamal Nasraoui Ebana,19,Right Wing
8,Spain,6685,Mikel Oyarzabal Ugarte,21,Center Forward
13,Spain,11748,Unai Simón Mendibil,23,Goalkeeper
15,Spain,17620,Marc Cucurella Saseta,24,Left Back

In [9]:
centre_backs = players_played_clean[
    players_played_clean["main_position"].str.contains(
        "Center Back",
        case=False,
        na=False
    )
].copy()

centre_backs

,team,player_id,player_name,jersey_number,main_position
26,England,3244,John Stones,5,Right Center Back
46,England,34526,Marc Guehi,6,Left Center Back
16,Spain,22128,Robin Aime Robert Le Normand,3,Right Center Back
5,Spain,5202,José Ignacio Fernández Iglesias,4,Right Center Back
4,Spain,4353,Aymeric Laporte,14,Left Center Back

In [10]:
events = sb.events(match_id=MATCH_ID)

event_players = (
    events[["team", "player", "position"]]
    .dropna()
    .drop_duplicates()
    .sort_values(["team", "player"])
)

event_players

E:\Documents\mosda\Projets\Data analyse\Projet 1 -Heatmap de passes d’un défenseur central\central-defender-pass-heatmap\.venv\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

         team                           player                   position
65    England                      Bukayo Saka                 Right Wing
915   England                      Bukayo Saka      Right Center Midfield
733   England                      Cole Palmer  Center Attacking Midfield
22    England                      Declan Rice    Left Defensive Midfield
918   England                      Declan Rice  Center Defensive Midfield
63    England                       Harry Kane             Center Forward
1791  England                       Ivan Toney        Left Center Forward
120   England                      John Stones          Right Center Back
7     England                  Jordan Pickford                 Goalkeeper
14    England                  Jude Bellingham                  Left Wing
730   England                  Jude Bellingham   Right Defensive Midfield
6     England                    Kobbie Mainoo   Right Defensive Midfield
45    England                      Kyle Walker                 Right Back
21    England                        Luke Shaw                  Left Back
28    England                       Marc Guehi           Left Center Back
902   England                    Ollie Watkins             Center Forward
1794  England                    Ollie Watkins       Right Center Forward
43    England                       Phil Foden  Center Attacking Midfield
838   England                       Phil Foden                  Left Wing
18      Spain                  Aymeric Laporte           Left Center Back
10      Spain            Daniel Carvajal Ramos                 Right Back
13      Spain             Daniel Olmo Carvajal  Center Attacking Midfield
2884    Spain             Daniel Olmo Carvajal                 Right Wing
66      Spain                 Fabián Ruiz Peña    Left Defensive Midfield
864     Spain  José Ignacio Fernández Iglesias          Right Center Back
51      Spain      Lamine Yamal Nasraoui Ebana                 Right Wing
55      Spain            Marc Cucurella Saseta                  Left Back
485     Spain          Martín Zubimendi Ibáñez   Right Defensive Midfield
1793    Spain               Mikel Merino Zazón  Center Attacking Midfield
734     Spain           Mikel Oyarzabal Ugarte             Center Forward
60      Spain        Nicholas Williams Arthuer                  Left Wing
9       Spain     Robin Aime Robert Le Normand          Right Center Back
16      Spain       Rodrigo Hernández Cascante   Right Defensive Midfield
8       Spain              Unai Simón Mendibil                 Goalkeeper
11      Spain       Álvaro Borja Morata Martín             Center Forward

In [11]:
players_for_configs = players_played_clean.copy()

players_for_configs["match_id"] = 3943043
players_for_configs["competition_id"] = 55
players_for_configs["season_id"] = 282

players_for_configs = players_for_configs[
    [
        "competition_id",
        "season_id",
        "match_id",
        "team",
        "player_id",
        "player_name",
        "jersey_number",
        "main_position"
    ]
]

players_for_configs

,competition_id,season_id,match_id,team,player_id,player_name,jersey_number,main_position
29,55,282,3943043,England,3468,Jordan Pickford,1,Goalkeeper
25,55,282,3943043,England,3205,Kyle Walker,2,Right Back
28,55,282,3943043,England,3382,Luke Shaw,3,Left Back
34,55,282,3943043,England,3943,Declan Rice,4,Left Defensive Midfield
26,55,282,3943043,England,3244,John Stones,5,Right Center Back
46,55,282,3943043,England,34526,Marc Guehi,6,Left Center Back
41,55,282,3943043,England,22084,Bukayo Saka,7,Right Wing
40,55,282,3943043,England,10955,Harry Kane,9,Center Forward
45,55,282,3943043,England,30714,Jude Bellingham,10,Left Wing
36,55,282,3943043,England,4354,Phil Foden,11,Center Attacking Midfield
33,55,282,3943043,England,3834,Ivan Toney,17,Left Wing
37,55,282,3943043,England,4760,Ollie Watkins,19,Center Forward
47,55,282,3943043,England,39461,Cole Palmer,24,Right Defensive Midfield
49,55,282,3943043,England,99174,Kobbie Mainoo,26,Right Defensive Midfield
6,55,282,3943043,Spain,5721,Daniel Carvajal Ramos,2,Right Back
16,55,282,3943043,Spain,22128,Robin Aime Robert Le Normand,3,Right Center Back
5,55,282,3943043,Spain,5202,José Ignacio Fernández Iglesias,4,Right Center Back
0,55,282,3943043,Spain,3042,Mikel Merino Zazón,6,Right Wing
2,55,282,3943043,Spain,3477,Álvaro Borja Morata Martín,7,Center Forward
7,55,282,3943043,Spain,6655,Fabián Ruiz Peña,8,Left Defensive Midfield
14,55,282,3943043,Spain,16532,Daniel Olmo Carvajal,10,Center Attacking Midfield
4,55,282,3943043,Spain,4353,Aymeric Laporte,14,Left Center Back
10,55,282,3943043,Spain,6765,Rodrigo Hernández Cascante,16,Right Defensive Midfield
21,55,282,3943043,Spain,68574,Nicholas Williams Arthuer,17,Left Wing
17,55,282,3943043,Spain,24921,Martín Zubimendi Ibáñez,18,Right Defensive Midfield
23,55,282,3943043,Spain,316046,Lamine Yamal Nasraoui Ebana,19,Right Wing
8,55,282,3943043,Spain,6685,Mikel Oyarzabal Ugarte,21,Center Forward
13,55,282,3943043,Spain,11748,Unai Simón Mendibil,23,Goalkeeper
15,55,282,3943043,Spain,17620,Marc Cucurella Saseta,24,Left Back

In [12]:
from pathlib import Path

output_dir = Path("../outputs/players")
output_dir.mkdir(parents=True, exist_ok=True)

players_for_configs.to_csv(
    output_dir / "euro_2024_final_players.csv",
    index=False
)